### ISSUE TITLE
Spotilocal opens to a white screen window and instantly crashes

### ISSUE THREAD

**Issue by Gaemfreak** [jmswrnr/spotilocal#14]
I can't seem to get this to work. It crashes instantly but continues running in the background. I have to end task for it to go away. I've seen it load the Spotify page once but froze while I was typing in my credentials.
![image](https://github.com/user-attachments/assets/c71d3348-f728-4661-ba92-e18d90306e69)

**Comment by Gaemfreak** [comment]
This is in v0.0.15. v0.0.14 seems to work fine.

**Comment by jmswrnr** [comment]
Thanks for reporting I’ll investigate and attempt to reproduce this

I’m assuming you ran v0.0.15 initially and failed to login, without using an older version before that, is that correct?

**Comment by jmswrnr** [comment]
I can't seem to reproduce this, v0.0.15 allows me to login fine on a fresh machine. Was there any chance of you running multiple instances of the application? perhaps that would cause this issue.

Some more detailed steps to reproduce this issue would be helpful!

**Comment by jmswrnr** [comment]
As a precautionary measure I have prevented multiple instances being open in [v0.0.16](https://github.com/jmswrnr/spotilocal/releases/tag/v0.0.16), not sure if this was the root cause of this issue though.

**Comment by Gaemfreak** [comment]
> Thanks for reporting I’ll investigate and attempt to reproduce this
> 
> I’m assuming you ran v0.0.15 initially and failed to login, without using an older version before that, is that correct?

Yeah, the very first attempt at using the program was with v0.0.15. v0.0.16 seems to work for me.

I had one question, is there a way to edit what characters are between artist and track name? Snip had that as a feature, which let me format the text like this for easier readability with wraparound text: "The Cure - Disintegration - "

**Comment by jmswrnr** [comment]
> Yeah, the very first attempt at using the program was with v0.0.15. v0.0.16 seems to work for me. Thanks!

I've been able to confirm that running two instance of v0.0.15 without being logged into Spotify does cause strange issues but could not reproduce this issue exactly. Could you please log out of Spotify or delete `%appdata%/spotilocal` and attempt to load two instances of v0.0.15 to see if that reproduces your original issue? 

> I had one question, is there a way to edit what characters are between artist and track name? 

This is not yet implemented but I did create a placeholder issue for it (#13), I'll take a look at implementing that soon if you find it useful.

**Comment by Gaemfreak** [comment]
So I tried what you asked and when I opened the first instance of v0.0.15, nothing pops up asking me to sign in. If I open another instance while the first is running, nothing happens. No window opens. If I force close both instances through the task manager and open a third instance, I get the issue I previously reported.

**Comment by jmswrnr** [comment]
Amazing, thanks for testing that! I will now mark this issue as resolved.

If you notice an issue with v0.0.16+ not opening the login window on first launch without app data please open a new issue!
