### ISSUE TITLE
[Request] A 'Spotilocal_history' file

### ISSUE THREAD

**Issue by murko69** [jmswrnr/spotilocal#2]
Hi there. 
Since the idea of it all came from Snip I'm sure you're aware there's a choice to also save track history in a separate text file.
Just like the JSON-file, this file is not emptied.
```
track 1 - artist 1
track 2 - artist 2
track 3 - artist 3
```
etc

I use such a file for monthly statistics and then I save it as.... and manually empty the original and let it start over

I've been using Snip for many years and it has been working well most of the time, but the last year or so my experience is that on a 100 track run, there's 5-15 tracks missing in the history file due to slow updates!

Also I sometimes have issues with duplicates in the history file but I actually made an excel-sheet cleaning those up before I create my statistics, so even if you create such a file and it also would give my me duplicates from time to time I can live with that :)

About the duplicates I mean right after each-other.
It's like the connection breaks/re-connects somehow and then I can see the same info on 2-10 rows instead of just showing it one time since I very seldom play the same song twice in a row!

Been trying your application for about a week (I run it simultaneously as Snip, on another computer) and I can clearly see the difference in loading time for the text files and album cover. Color me impressed :)
So, that's why I really would like to see a history file as well!

Regards
/michael

**Comment by jmswrnr** [comment]
Hey thanks for requesting this, I'll take a look to see how that would work with this project.

**Comment by jmswrnr** [comment]
I've added a track history feature into the new [v0.0.15 release ](https://github.com/jmswrnr/spotilocal/releases/tag/v0.0.15)!

Please let me know if you have any issues with it, it will export a txt file where the latest song is at the bottom, and also a CSV format including timestamps.

**Comment by jmswrnr** [comment]
Oh I've also added some logic to reduce duplicates, if you pause/play/scrub a track or reload the app it will not cause a duplicate entry, it will only add if you reload Spotify player, or change to a different track 👍

**Comment by murko69** [comment]
I'll give it a spin in a few minutes. I will try and compare in a day or so and see what is what!
Thanks also for the CSV and the extra logic 😀
